language: R
cache:                          # optional
  packages: true                # optional
directories: _bookdown_files  # optional
pandoc_version: 2.3.1

repos:
  cran: http://cran.rstudio.com
  rforge: http://R-Forge.R-project.org


r_github_packages:
 - coatless/ucidata
 - hrbrmstr/statebins

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  github-token: $GITHUB_TOKEN    # Set in the Travis cc19 settings page
  on:
    branch: master
